spring.application.name=pool-api

spring.datasource.url=jdbc:postgresql://localhost:5432/pool_db
spring.datasource.username=postgres
spring.datasource.password=Toto1982!!!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.jpa.open-in-view=false

spring.jackson.mapper.default-view-inclusion=true

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

jwt.secret=3da6e053d0095ff494d8ff6865f8ec10660b67dd59f0f073c9736b05438db31e
jwt.expiration=86400000